export const Constant ={
    DOMAIN: "https://localhost:7240/",
    API_VER: "api/v1/",
    MATERIAL_PATH: "Materials",
    UNIT_PATH: "Units",
    STOCK_PATH: "Stocks",
    CONVERSION_UNIT_PATH: "ConversionUnits",
    REF_FISRT_INPUT: "FirstInput",
    REF_STOCK_NAME: "StockName",
    REF_UNIT: "Unit",
    REF_MATERIAL_NAME: "MaterialName",
    REF_MATERIAL_CODE: "MaterialCode",
    EMIT_UPDATE_NAME: "update:Name",
    EMIT_UPDATE_ID: "update:ID",
    EMIT_UPDATE_ISSHOW: "update:isShow",
    EMIT_UPDATE_PAGESIZE: "update:pageSize",
    EMIT_UPDATE_OPTIONID: "update:optionID",
    EMIT_UPDATE_VALUE: "update:value",
    EMIT_VALIDATE_UNIT: "validateUnit",
    EMIT_LOAD_UNIT: "loadUnit",
    EMIT_LOAD_STOCK: "loadStock",
    EMIT_LOAD_DATA: "LoadData",
    EMIT_SHOW_ALERT: "showAlert",
    EMIT_ADD_EVENT: "AddEvent",
    EMIT_ADD: "addValue",
    EMIT_FOCUS: "focus",
    EMIT_YES_CLICK: "onYesClick",
    EMIT_NO_CLICK: "onNoClick",
    EMIT_PAGESIZE: "PageSize",
    EMIT_STATUS: "Status",
    EMIT_FILLTER: "fillter",
    EMIT_UPDATE_ACTION_TYPE:"update:ActionType",
    EMIT_REMOVE_EVENT:"removeEvent",
    EMIT_UPDATE_TITLE:"update:Title",
    EMIT_FORMATDATE: "formatDate",
    EMIT_SHOW:"getEmitShow",
    BORDER_CLASS: "border-red",
    TEXT_ADD: "%2B",
    KEY_EVENT:"keydown",
}