export const Resources = {
    DOMAIN: "https://localhost:7240/",
    API_VER: "api/v1/",
    MATERIAL_PATH: "Materials",
    UNIT_PATH:"Units",
   STOCK_PATH: "Stocks",
   CONVERSION_UNIT_PATH:"ConversionUnits",
   MATERIALE_CODE_ERROR:"Mã không được để trống!",
   MATERIAL_NAME_ERROR:"Tên không được để trống!",
    UNIT_ERROR:"Đơn vị Không được để trống!",
    ID_NOT_FOUND: "Nhân viên không tồn tại trong hệ thống hoặc đã bị xóa trước đó.",
    UNDEFINED_ERROR:"Có lỗi xảy ra! Vui lòng liên hệ MISA.",
    DOWNLOAD_SUCCESS:"Tải danh sách nhân viên thành công.",
    UPDATE_SUCCESS:"Cập nhật nhân viên thành công.",
    INSERT_SUCCESS:"Thêm mới nhân viên thành công.",
    DELETE_SUCCESS:"Xóa nhân viên thành công.",
    DELETE_CONFIRM:"Bạn có thực sự muốn xóa những nhân viên đã chọn không?",
    DELETE_MULTIPLE_CONFRIM:"Bạn có thực sự muốn xóa những nhân viên đã chọn không?",
    CLOSE_CONFIRM:"Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
    UNIT_TITLE:"Thêm đơn vị",
    STOCK_TITLE:"Thêm Kho",
    UNIT_LABEL: "Đơn vị",
    STOCK_LABEL: "Mã Kho"
};
