export const Resources = {
    MATERIALE_CODE_ERROR: "Mã không được để trống!",
    MATERIAL_NAME_ERROR: "Tên không được để trống!",
    UNIT_ERROR: "Đơn vị không được để trống!",
    STOCK_CODE_ERROR: "Mã kho không được để trống!",
    STOCK_NAME_ERROR: "Tên kho không được để trống!",
    ID_NOT_FOUND: "Nhân viên không tồn tại trong hệ thống hoặc đã bị xóa trước đó.",
    DUPLICATE_UNIT: "Tên đơn vị đã tồn tại trong hệ thống",
    DUPLICATE_STOCK: "Mã kho đã tồn tại trong hệ thống",
    UNDEFINED_ERROR: "Có lỗi xảy ra! Vui lòng liên hệ MISA.",
    UPDATE_SUCCESS: "Cập nhật nguyên vật liệu thành công.",
    INSERT_SUCCESS: "Thêm mới nguyên vật liệu thành công.",
    INSERT_UNIT_SUCCESS: "Thêm mới đơn vị thành công.",
    INSERT_STOCK_SUCCESS: "Thêm mới kho thành công.",
    DELETE_SUCCESS: "Xóa nguyên vật liệu thành công.",
    CLOSE_CONFIRM: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
    UNIT_CHANGE_DUPLICATE: "Đơn vị chuyển đổi không được trùng nhau!",
    UNIT_CHANGE_ERROR: "Đơn vị chuyển đổi không được trùng với đơn vị chính!",
    ADD_TITLE: "Thêm",
    UPDATE_TITLE: "Sửa",
    UNIT_TITLE: "Thêm đơn vị",
    STOCK_TITLE: "Thêm Kho",
    UNIT_LABEL: "Đơn vị",
    STOCK_LABEL: "Mã Kho"
};
