export const Resources = {
    DOMAIN: "https://localhost:7240/",
    API_VER: "api/v1/",
    MATERIAL_PATH: "Materials",
    DEPARTMENT_PATH:"Departments",
    EXCEL_FILE:"Danh sach nhan vien.xlsx",
    OPTION_CONTENT: " bản ghi trên 1 trang",
    EMPLOYEE_CODE_NULL:"Mã không được để trống!",
    EMPLOYEE_CODE_ERROR:"Mã không đúng định dạng!",
    EMPLOYEE_NAME_ERROR:"Tên không được để trống!",
    DEPARTMENT_ERROR:"Đơn vị Không được để trống!",
    DOB_ERROR:"Ngày sinh không được lớn hơn ngày hiện tại!",
    IDENTITY_DATE_ERROR:"Ngày cấp không được lớn hơn ngày hiện tại!",
    EMAIL_ERROR:"Email không đúng định dạng!",
    MOBIBLE_PHONE_ERROR:"Số điện thoại di động không đúng định dạng!",
    LANDLINE_PHONE_ERROR:"Số điện thoại cố định không đúng định dạng!",
    ID_NOT_FOUND: "Nhân viên không tồn tại trong hệ thống hoặc đã bị xóa trước đó.",
    UNDEFINED_ERROR:"Có lỗi xảy ra! Vui lòng liên hệ MISA.",
    DOWNLOAD_SUCCESS:"Tải danh sách nhân viên thành công.",
    UPDATE_SUCCESS:"Cập nhật nhân viên thành công.",
    INSERT_SUCCESS:"Thêm mới nhân viên thành công.",
    DELETE_SUCCESS:"Xóa nhân viên thành công.",
    DELETE_CONFIRM:"Bạn có thực sự muốn xóa những nhân viên đã chọn không?",
    DELETE_MULTIPLE_CONFRIM:"Bạn có thực sự muốn xóa những nhân viên đã chọn không?",
    CLOSE_CONFIRM:"Dữ liệu đã bị thay đổi. Bạn có muốn cất không?"
};
